services:
  app:
    image: ohio-order
    build:
      context: .
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "8080:8080"

  postgres:
    image: postgres:17
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: