# fly.toml app configuration file generated for a08-ohio-order on 2025-04-11T20:16:47+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'a08-ohio-order'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
